// Generated by CoffeeScript 1.7.1
(function() {
  var Dgroupe, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof window !== "undefined" && window !== null ? window : global;

  Dgroupe = root.Dgroupe;

  Dgroupe.Models.GalleryImg = (function(_super) {
    __extends(GalleryImg, _super);

    function GalleryImg() {
      return GalleryImg.__super__.constructor.apply(this, arguments);
    }

    GalleryImg.prototype.defaults = {
      title: 'Gallery Title',
      galleryItems: [
        {
          title: 'Image title',
          thumbnail: 'src path',
          fullImg: 'src path'
        }, {
          title: 'Image title',
          thumbnail: 'src path',
          fullImg: 'src path'
        }
      ]
    };

    return GalleryImg;

  })(Backbone.Model);

  Dgroupe.Collections.Gallery = (function(_super) {
    __extends(Gallery, _super);

    function Gallery() {
      return Gallery.__super__.constructor.apply(this, arguments);
    }

    Gallery.prototype.model = Dgroupe.Models.GalleryImg;

    Gallery.prototype.url = '/json-gallery';

    Gallery.prototype.initialize = function(options) {
      var _ref;
      this.url = this.url + ((_ref = options != null ? options.urlQuery : void 0) != null ? _ref : '');
      return console.log('@url', this.url);
    };

    Gallery.prototype.parse = function(response, options) {
      console.log('parsing response', response);
      this.pageQ = response.pageQ;
      return response.galleries;
    };

    return Gallery;

  })(Dgroupe.Collections.Paginated);

}).call(this);

//# sourceMappingURL=galleries.map
