// Generated by CoffeeScript 1.7.1
(function() {
  var Dgroupe, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof window !== "undefined" && window !== null ? window : global;

  Dgroupe = root.Dgroupe;

  Dgroupe.Views.BaseContent = (function(_super) {
    __extends(BaseContent, _super);

    function BaseContent() {
      return BaseContent.__super__.constructor.apply(this, arguments);
    }

    BaseContent.prototype.initialize = function() {
      return this.listenTo(this.model, 'sync', this.render);
    };

    BaseContent.prototype.render = function(callback) {
      if (_.isEmpty(this.model.toJSON())) {
        console.log('model is empty, fetching it now');
        this.model.fetch();
      } else {
        console.log('model fetched, now rendering');
        this.$el.html(this.template(this.model.toJSON()));
      }
      if (_.isFunction(callback)) {
        callback();
      }
      return this;
    };

    return BaseContent;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=base-content.map
