// Generated by CoffeeScript 1.7.1
(function() {
  var Dgroupe, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof window !== "undefined" && window !== null ? window : global;

  Dgroupe = root.Dgroupe;

  Dgroupe.Views.gallery = (function(_super) {
    __extends(gallery, _super);

    function gallery() {
      return gallery.__super__.constructor.apply(this, arguments);
    }

    return gallery;

  })(Dgroupe.Views.ColectionView);

}).call(this);

//# sourceMappingURL=gallery.map
