// Generated by CoffeeScript 1.7.1
(function() {
  var Dgroupe, root,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof window !== "undefined" && window !== null ? window : root;

  Dgroupe = root.Dgroupe;

  Dgroupe.Views.MainLoader = (function(_super) {
    __extends(MainLoader, _super);

    function MainLoader() {
      this.hide = __bind(this.hide, this);
      this.show = __bind(this.show, this);
      return MainLoader.__super__.constructor.apply(this, arguments);
    }

    MainLoader.prototype.className = 'progress';

    MainLoader.prototype.id = 'mainLoader';

    MainLoader.prototype.initialize = function() {
      if ($('#' + this.id)[0] != null) {
        this.setElement('#' + this.id);
      }
      this.hideClass = 'hidden';
      $(document).on('showLoader', this.show);
      $(document).on('hideLoader', this.hide);
      return this.render();
    };

    MainLoader.prototype.show = function() {
      console.log('showing loader');
      return this.$el.removeClass(this.hideClass);
    };

    MainLoader.prototype.hide = function() {
      console.log('hiding loader');
      return this.$el.addClass(this.hideClass);
    };

    return MainLoader;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=loader.map
