// Generated by CoffeeScript 1.7.1
(function() {
  var Dgroupe, root,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof window !== "undefined" && window !== null ? window : global;

  Dgroupe = root.Dgroupe;

  Dgroupe.Views.navigation = (function(_super) {
    __extends(navigation, _super);

    function navigation() {
      this.markAsSelected = __bind(this.markAsSelected, this);
      this.navigate = __bind(this.navigate, this);
      this.navHandler = __bind(this.navHandler, this);
      return navigation.__super__.constructor.apply(this, arguments);
    }

    navigation.prototype.el = '#NavBar';

    navigation.prototype.initialize = function() {
      this.$navItems = this.$el.find('a');
      return this.currentRoute = '';
    };

    navigation.prototype.events = {
      'click a': 'navHandler'
    };

    navigation.prototype.navHandler = function(e) {
      var $currentTarget, linkTarget;
      e.stopPropagation();
      e.preventDefault();
      $currentTarget = $(e.currentTarget);
      linkTarget = $currentTarget.attr('href');
      return this.navigate(linkTarget, $currentTarget);
    };

    navigation.prototype.navigate = function(linkTarget, $currentTarget) {
      var e;
      this.markAsSelected($currentTarget);
      try {
        App.navigate(linkTarget, true);
        return this.currentRoute = linkTarget;
      } catch (_error) {
        e = _error;
        throw new Error('This method needs a router instance defined named "app"');
      }
    };

    navigation.prototype.markAsSelected = function($el) {
      var $closestUl, selectedClass;
      selectedClass = 'current_page_item';
      $closestUl = $el.closest('ul');
      if ($closestUl.hasClass('subLvl')) {
        $closestUl.closest('.mainLvl').addClass(selectedClass);
      } else {
        $('.mainLvl').removeClass(selectedClass);
      }
      this.$navItems.removeClass(selectedClass);
      return $el.addClass(selectedClass);
    };

    navigation.prototype.findCurrentRoute = function(route) {
      var el, elLink, index, _i, _len, _ref;
      index = 0;
      _ref = this.$navItems;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        el = _ref[_i];
        elLink = $(el).attr('href');
        if (elLink.indexOf(route) !== -1) {
          break;
        } else {
          index++;
        }
      }
      return this.markAsSelected($(this.$navItems[index]));
    };

    return navigation;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=navigator.map
