// Generated by CoffeeScript 1.7.1
(function() {
  var Dgroupe, root,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof window !== "undefined" && window !== null ? window : global;

  Dgroupe = root.Dgroupe;

  Dgroupe.Views.News = (function(_super) {
    __extends(News, _super);

    function News() {
      this.showFullEntry = __bind(this.showFullEntry, this);
      return News.__super__.constructor.apply(this, arguments);
    }

    News.prototype.tagName = 'ul';

    News.prototype.className = 'grid';

    News.prototype.id = 'newsFeed';

    News.prototype.events = {
      'click a': 'showFullEntry'
    };

    News.prototype.initialize = function(options) {
      News.__super__.initialize.apply(this, arguments);
      if ($('#' + this.id)[0] != null) {
        return this.setElement('#' + this.id);
      }
    };

    News.prototype.showFullEntry = function(e) {
      var $targetLink;
      e.preventDefault();
      e.stopPropagation();
      $targetLink = $(e.currentTarget).attr('href');
      Backbone.history.navigate($targetLink, true);
      return null;
    };

    return News;

  })(Dgroupe.Views.CollectionView);

  Dgroupe.Views.NewsEntry = (function(_super) {
    __extends(NewsEntry, _super);

    function NewsEntry() {
      return NewsEntry.__super__.constructor.apply(this, arguments);
    }

    NewsEntry.prototype.tagName = 'li';

    NewsEntry.prototype.className = 'grid entry';

    NewsEntry.prototype.template = template('newsEntryTemplate');

    NewsEntry.prototype.render = function() {
      this.$el.html(this.template(this.model.toJSON()));
      return this;
    };

    return NewsEntry;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=news.map
