// Generated by CoffeeScript 1.7.1
(function() {
  var Dgroupe, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof window !== "undefined" && window !== null ? window : global;

  Dgroupe = root.Dgroupe;

  Dgroupe.Views.SingleEntry = (function(_super) {
    __extends(SingleEntry, _super);

    function SingleEntry() {
      return SingleEntry.__super__.constructor.apply(this, arguments);
    }

    SingleEntry.prototype.template = root.template('fullEntryTemplate');

    SingleEntry.prototype.tagName = 'article';

    SingleEntry.prototype.className = 'fullEntry';

    SingleEntry.prototype.id = 'singleEntry';

    SingleEntry.prototype.events = {
      'click a': 'backToNews'
    };

    SingleEntry.prototype.initialize = function() {
      SingleEntry.__super__.initialize.apply(this, arguments);
      if ($('#' + this.id)[0] != null) {
        return this.setElement('#' + this.id);
      }
    };

    SingleEntry.prototype.backToNews = function(e) {
      var route;
      e.preventDefault();
      e.stopPropagation();
      route = $(e.currentTarget).attr('href');
      return Backbone.history.navigate(route, true);
    };

    return SingleEntry;

  })(Dgroupe.Views.BaseContent);

}).call(this);

//# sourceMappingURL=single-entry.map
