// Generated by CoffeeScript 1.7.1
(function() {
  var Dgroupe, root,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof window !== "undefined" && window !== null ? window : global;

  Dgroupe = root.Dgroupe;

  Dgroupe.Views.SlimGallery = (function(_super) {
    __extends(SlimGallery, _super);

    function SlimGallery() {
      this.lightboxHandler = __bind(this.lightboxHandler, this);
      return SlimGallery.__super__.constructor.apply(this, arguments);
    }

    SlimGallery.prototype.tagName = 'div';

    SlimGallery.prototype.className = 'grid';

    SlimGallery.prototype.events = {
      'click img': 'lightboxHandler'
    };

    SlimGallery.prototype.initialize = function(options) {
      var _ref;
      this.mode = (_ref = options.mode) != null ? _ref : 'images';
      if ($('#' + this.id) != null) {
        this.setElement('#' + this.id);
        return this.populateGalItems();
      }
    };

    SlimGallery.prototype.lightboxHandler = function(e) {
      var index;
      e.preventDefault();
      this.setLightBox();
      index = parseInt($(e.currentTarget).data('index'));
      return this.openLightBox(index);
    };

    SlimGallery.prototype.setLightBox = function() {
      return $.event.trigger({
        type: 'setLightbox',
        mode: this.mode,
        collection: this.galleryItems
      });
    };

    SlimGallery.prototype.openLightBox = function(index) {
      return $.event.trigger({
        type: 'showLightBox',
        modelIndex: index
      });
    };

    SlimGallery.prototype.populateGalItems = function() {
      var galleryItems, linkTargetKey;
      linkTargetKey = this.mode === 'images' ? 'fullImg' : 'embedUrl';
      galleryItems = [];
      this.$('a').each(function() {
        var $link, json;
        json = {};
        $link = $(this);
        json.title = $link.attr('title');
        json[linkTargetKey] = $link.attr('href');
        json.thumbnail = $link.find('img').attr('src');
        return galleryItems.push(json);
      });
      return this.galleryItems = new Backbone.Collection(galleryItems);
    };

    return SlimGallery;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=slim-gallery.map
