// Generated by CoffeeScript 1.7.1
(function() {
  var $, DEBUG, Slider, root,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  root = typeof window !== "undefined" && window !== null ? window : global;

  root.sliders = {};

  $ = root.jQuery;

  DEBUG = false;

  Slider = (function() {
    function Slider(sliderId, config) {
      var _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8;
      this.sliderId = sliderId;
      if (config == null) {
        config = {};
      }
      this.dragg = __bind(this.dragg, this);
      $ = window.jQuery;
      this.settings = {
        cycle: (_ref = config.cycle) != null ? _ref : true,
        navigator: (_ref1 = config.navigator) != null ? _ref1 : true,
        navigatorEvents: (_ref2 = config.navigatorEvents) != null ? _ref2 : false,
        duration: (_ref3 = config.duration) != null ? _ref3 : 1,
        emmitEvents: (_ref4 = config.emmitEvents) != null ? _ref4 : false,
        draggable: (_ref5 = config.draggable) != null ? _ref5 : true,
        centerImages: (_ref6 = config.centerImages) != null ? _ref6 : true,
        navigatorInParent: (_ref7 = config.navigatorInParent) != null ? _ref7 : false,
        preventLinksOnDrag: (_ref8 = config.allowLinks) != null ? _ref8 : false
      };
      this.$sliderViewport = $('#' + sliderId);
      this.$slider = $(this.$sliderViewport.children('.slider'));
      this.$sliderItems = $(this.$slider.children('li'));
      this.$sliderPrevBtn = $(this.$sliderViewport.children('.prevBtn'));
      this.$sliderNextBtn = $(this.$sliderViewport.children('.nextBtn'));
      this.startSlider();
    }

    Slider.prototype.config = function(property, value) {
      this.settings[property] = value;
      return this;
    };

    Slider.prototype.startSlider = function() {
      this.setSlider();
      if (this.elementsQ > 1) {
        return this.setListeners();
      } else {
        return this.disableBtns();
      }
    };

    Slider.prototype.setSlider = function() {
      var sliderItemWidth;
      this.viewPortWidth = this.$sliderViewport.width();
      this.elementsQ = this.$sliderItems.length;
      this.sliderWidth = this.elementsQ * 100;
      this.percentageStep = sliderItemWidth = 100 / this.elementsQ;
      this.rightLimit = (this.viewPortWidth * this.elementsQ) - this.viewPortWidth;
      this.$sliderItems.css('width', "" + sliderItemWidth + "%");
      this.$slider.css({
        'width': "" + this.sliderWidth + "%",
        'transition-duration': "" + this.settings.duration + "s"
      });
      if (this.settings.preventLinksOnDrag) {
        if (this.$sliderLinks == null) {
          this.$sliderLinks = this.$sliderItems.children().children();
        }
      }
      if (this.settings.navigatorInParent) {
        if (this.$sliderNavBtns == null) {
          this.$sliderNavBtns = $(this.$sliderViewport.parent().find('.navigator a'));
        }
      } else {
        if (this.$sliderNavBtns == null) {
          this.$sliderNavBtns = $(this.$sliderViewport.children('.navigator').children());
        }
      }
      this.index = 0;
      this.slideToPos = 0;
      this.draggedEl = null;
      this.hasLimitClass = false;
      return this;
    };

    Slider.prototype.setListeners = function() {
      this.$sliderPrevBtn.click((function(_this) {
        return function(e) {
          e.stopPropagation();
          return _this.slideTo('prev');
        };
      })(this));
      this.$sliderNextBtn.click((function(_this) {
        return function(e) {
          e.stopPropagation();
          return _this.slideTo('next');
        };
      })(this));

      /*
      Disabled for dgroupe, was causing a bug, so this a dirt hack, later should be refactored.
      @$sliderNavBtns.mousedown (e)=>
        e.stopPropagation()
        index = $(e.currentTarget).index()
        @slideTo(index)
       */
      if (this.settings.draggable) {
        this.$sliderViewport.on('click a', (function(_this) {
          return function(e) {
            e.preventDefault();
            return e.stopPropagation();
          };
        })(this));
        this.$sliderViewport.find('a').on('mousedown', (function(_this) {
          return function(e) {
            console.log('currentTarget', e.currentTarget);
            _this.linkTarget = $(e.currentTarget).attr('href');
            if (_this.settings.preventLinksOnDrag) {
              Backbone.history.navigate(_this.linkTarget, true);
              return _this.linkTarget = null;
            }
          };
        })(this));
        this.$sliderViewport.on('mousedown :not(.prevBtn)', (function(_this) {
          return function(e) {
            console.log('mousedown');
            e.stopPropagation();
            e.preventDefault();
            _this.draggedEl = e.currentTarget;
            _this.dragStart(e.pageX);
            return null;
          };
        })(this));
        this.$sliderViewport.on('touchstart', (function(_this) {
          return function(e) {
            var x;
            e = e.originalEvent;
            x = e.touches[0].pageX;
            _this.draggedEl = e.currentTarget;
            _this.dragStart(x, 'touchmove');
            return null;
          };
        })(this));
        $(document).on('mouseup', (function(_this) {
          return function(e) {
            e.stopPropagation();
            e.preventDefault();
            return _this.dragEnd(e.pageX);
          };
        })(this));
        this.$sliderViewport.on('touchend', (function(_this) {
          return function(e) {
            var x;
            console.log('e.originalEvent', e.originalEvent);
            x = e.originalEvent.touches[0].pageX;
            return _this.dragEnd(x);
          };
        })(this));
      }
      return $(window).resize((function(_this) {
        return function() {
          return setTimeout(function() {
            return _this.setSlider();
          }, 1);
        };
      })(this));
    };

    Slider;

    Slider.prototype.disableBtns = function() {
      this.$sliderPrevBtn.css('opacity', 0.2);
      this.$sliderNextBtn.css('opacity', 0.2);
      return this;
    };

    Slider.prototype.dragStart = function(startX, inputEvent) {
      var $el, dragPos, slideToPos;
      if (inputEvent == null) {
        inputEvent = 'mousemove';
      }
      $el = $(this.draggedEl);
      this.dragStartX = startX;
      slideToPos = this.$slider.position().left;
      dragPos = (slideToPos / this.viewPortWidth) * 100;
      this.$slider.css({
        'transition-duration': '0s'
      });
      return $el.on(inputEvent, (function(_this) {
        return function(ev) {
          var x;
          ev = ev.originalEvent;
          x = inputEvent === 'mousemove' ? ev.pageX : ev.touches[0].pageX;
          return _this.dragg(startX, x, slideToPos);
        };
      })(this));
    };

    Slider.prototype.dragg = function(startX, currentX, slideToPos) {
      var dragPos, offsetX;
      offsetX = startX - currentX;
      slideToPos -= offsetX;
      if (slideToPos >= 0) {
        slideToPos = 0;
        this.isOutBounds = true;
        this.dragStartX = currentX;
        if (!this.hasLimitClass) {
          this.$sliderViewport.addClass('onLeftLimit');
          this.hasLimitClass = true;
        }
      } else if (slideToPos <= -this.rightLimit) {
        slideToPos = -this.rightLimit;
        this.isOutBounds = true;
        this.dragStartX = currentX;
        if (!this.hasLimitClass) {
          this.$sliderViewport.addClass('onRightLimit');
          this.hasLimitClass = true;
        }
      }
      dragPos = (slideToPos / this.viewPortWidth) * 100;
      dragPos = dragPos * (this.percentageStep / 100);
      this.$slider.css('transform', "translate3d(" + dragPos + "%, 0, 0)");
      this.isOutBounds = false;
      return null;
    };

    Slider.prototype.dragEnd = function(currentX) {
      var minToAction, offsetPercentage, offsetX, tempIndex;
      if (this.draggedEl || this.clicked) {
        console.log('drag end event fired for ' + this.sliderId);
        console.log(this.draggedEl);
        if (this.hasLimitClass) {
          this.$sliderViewport.removeClass('onLeftLimit onRightLimit');
          this.hasLimitClass = false;
        }
        offsetX = this.dragStartX - currentX;
        offsetPercentage = Math.abs(offsetX / this.viewPortWidth);
        minToAction = 0.1;
        if (offsetPercentage < minToAction) {
          offsetPercentage = 0;
        }
        if (offsetX > 0 && !this.isOutBounds) {
          console.log("Dragued-> right");
          tempIndex = this.index + Math.ceil(offsetPercentage);
        } else if (offsetX < 0 && !this.isOutBounds) {
          console.log("Dragued-> left");
          tempIndex = this.index - Math.ceil(offsetPercentage);
        } else {
          console.log("Didn't move, or at least not much");
          tempIndex = this.index;
          if (this.linkTarget != null) {
            console.log('Navigating to the previously clicked link', this.linkTarget);
            Backbone.history.navigate(this.linkTarget, true);
            this.linkTarget = null;
          }
        }
        console.log("tempIndex:" + tempIndex);
        this.slideTo(tempIndex);
        $(this.draggedEl).off('mousemove');
        this.draggedEl = null;
        console.log(this.draggedEl);
        return false;
      }
    };


    /*
     * Moves the slider to the prev, next, or an specific position based on the command argument
     * @param {string}|{integer} command
     * @return {void}
     */

    Slider.prototype.slideTo = function(command) {
      var err, lastIndx, slideToPos;
      this.clicked = null;
      console.log('slideTo Called with argument:' + command);
      switch (command) {
        case 'next':
          this.index++;
          break;
        case 'prev':
          this.index--;
          break;
        case 'first':
          this.index = 0;
          break;
        case 'last':
          this.index = this.elementsQ - 1;
          break;
        default:
          if (isFinite(command)) {
            this.index = command;
          } else {
            err = 'Please provide a valid command for the slider [prev,next or a valid index]';
            console.error(err);
            return false;
          }
      }
      lastIndx = this.elementsQ - 1;
      if (this.index > lastIndx) {
        if (this.settings.cycle) {
          this.index = 0;
        } else {
          this.index = lastIndx;
          return false;
        }
      } else if (this.index < 0) {
        if (this.settings.cycle) {
          this.index = lastIndx;
        } else {
          this.index = 0;
          return false;
        }
      }
      console.log('index:' + this.index);
      slideToPos = -1 * (this.index * this.percentageStep);
      if (this.settings.navigator) {
        this.$sliderNavBtns.removeClass('selected');
        $(this.$sliderNavBtns[this.index]).addClass('selected');
      }
      this.$slider.css({
        'transform': "translate3d(" + slideToPos + "%, 0, 0)",
        'transition-duration': "" + this.settings.duration + "s"
      });
      if (this.settings.emmitEvents) {
        $.event.trigger('onSlide', [this.index, this.sliderId]);
      }
      return this;
    };

    return Slider;

  })();

  $(function() {
    var djHouse, frameName, sectionName, sliderId, sliderName, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2;
    window.sliders.main = new Slider('mainSlider', {
      autoHideBtns: true,
      emmitEvents: true
    });
    _ref = ['frameMusicSldr', 'frameOnSldr', 'frameCorpSldr', 'frameEventsSldr'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      frameName = _ref[_i];
      new Slider(frameName, {});
    }
    _ref1 = ['on', 'music', 'events', 'corp'];
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      sectionName = _ref1[_j];
      sectionName += 'Section';
      sliderName = "" + sectionName + "Sldr";
      window.sliders[sectionName] = new Slider(sliderName, {
        emmitEvents: true,
        navigator: true,
        navigatorInParent: true,
        navigatorEvents: false
      });
    }
    _ref2 = ['kukaramakara', 'lussac', 'sixttina', 'delaire', 'lussac'];
    for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
      djHouse = _ref2[_k];
      sliderId = "" + djHouse + "DjSlider";
      new Slider(sliderId, {
        emmitEvents: false,
        autoHideBtns: true,
        draggable: false
      });
    }
    $('.socialBlock').click(function(e) {
      return e.stopPropagation();
    });
    return $('#newsWrapper, .socialBlock, .pageNavi').on({
      click: function(e) {
        return e.stopPropagation();
      },
      mousedown: function(e) {
        return e.stopPropagation();
      }
    });
  });

}).call(this);

//# sourceMappingURL=drag-slider.map
